In [1]:
import pandas as pd
import numpy as np

In [2]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [3]:
df = pd.concat([flats,houses], ignore_index=True)

In [4]:
df = df.sample(df.shape[0],ignore_index=True)

In [5]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,4 BHK Flat in Sector 22 Gurgaon,ambience creacions,6.00,20533.0,29221.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5...",NaN
1,3 BHK Flat in Sector-2 Sohna,supertech hill town,1.00,8720.0,11468.0,Carpet area: 1720 (159.79 sq.m.),3,3,3+,not available,"L342c, Sector-2 Sohna, Gurgaon, Haryana",3.0,East,Under Construction,"['Discount Department Store', 'Omaxe Gurgaon M...","Spacious rooms, amazing locality, situated on ...",[],"['Lift(s)', 'Maintenance Staff', 'Swimming Poo...",NaN,NaN
2,2 BHK Flat in Sector 107 Gurgaon,m3m woodshire,1.00,7496.0,13340.0,Super Built up area 1534(142.51 sq.m.)Carpet a...,2,2,3,study room,"Sector 107 Gurgaon, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Ground floor corner flat with day light throug...,"['5 Fan', '1 Geyser', '5 Light', '4 AC', '1 Mo...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction5 out ...",NaN
3,5 Bedroom House for sale in Sector 57 Gurgaon,satya the legend,9.25,16577.0,5580.0,Plot area 642(536.79 sq.m.)Built Up area: 630 ...,5,5,3+,"study room,servant room,pooja room,store room","7-08, Sector 57 Gurgaon, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['HDFC Bank ATM', 'ICICI Bank ATM', 'YES Bank ...","Sector-57, gurgaon is located on the golf cour...","['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4 out of 5', 'Safety4 out of 5', ...",house
4,2 BHK Flat in Sector 83 Gurgaon,vatika gurgaon,0.07,6265.0,1117.0,Super Built up area 1245(115.66 sq.m.)Built Up...,2,2,2,"pooja room,study room","1102, Sector 83 Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Luxurious 2 bhk apartment for sell in sector-8...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '5 Ligh...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ...",NaN

In [6]:
df.to_csv('gurgoan_properties.csv',index=False)

In [7]:
df.shape

(3961, 20)